### ISSUE TITLE
gdata.youtube.com/feeds/api/users/username/uploads

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/google-gdata#718]
```
What steps will reproduce the problem?
1.Go to http://gdata.youtube.com/feeds/api/users/username/uploads
2.I receive "No longer available" or "HTTP 410 Gone"
3.!!!!!

What is the expected output? List of the videos
 What do you see instead?No longer available


What version of the product are you using? On what operating system?


Please provide any additional information below.

```

Original issue reported on code.google.com by `AmrAhmed...@gmail.com` on 7 Jun 2015 at 5:15

**Comment by oskar-j** [comment]
It's my first time with the `gdata` package and I'm facing a similar issue. Is it a recent thing or there is something wrong with my code?

```
import sys
from gdata.youtube import service

USERNAME = sys.argv[1]  # 'username@gmail.com'
PASSWORD = sys.argv[2]  # 'a_very_long_password'
VIDEO_ID = sys.argv[3]  # 'wf_IIbT8HGk'

def comments_generator(client, video_id):
    comment_feed = client.GetYouTubeVideoCommentFeed(video_id=video_id)
    while comment_feed is not None:
        for comment in comment_feed.entry:
             yield comment
        next_link = comment_feed.GetNextLink()
        if next_link is None:
             comment_feed = None
        else:
             comment_feed = client.GetYouTubeVideoCommentFeed(next_link.href)

client = service.YouTubeService()
client.ClientLogin(USERNAME, PASSWORD)

with open("comments_tymbark.tsv", "wb") as output:
    for comment in comments_generator(client, VIDEO_ID):
        author_name = comment.author[0].name.text
        text = comment.content.text
        comment_id = comment.id
        updated = comment.updated
        print("{0}\t{1}\t{2}\t{3}\n".format(author_name, text, comment_id, updated))
        output.write("{0}\t{1}\t{2}\t{3}\n".format(author_name, text, comment_id, updated))

```

```
Traceback (most recent call last):
  File "dataset.py", line 24, in <module>
    for comment in comments_generator(client, VIDEO_ID):
  File "dataset.py", line 9, in comments_generator
    comment_feed = client.GetYouTubeVideoCommentFeed(video_id=video_id)
  File "C:\Python27\lib\site-packages\gdata\youtube\service.py", line 270, in Ge
tYouTubeVideoCommentFeed
    uri, converter=gdata.youtube.YouTubeVideoCommentFeedFromString)
  File "C:\Python27\lib\site-packages\gdata\service.py", line 1108, in Get
    'reason': server_response.reason, 'body': result_body}
gdata.service.RequestError: {'status': 410, 'body': 'No longer available', 'reas
on': 'Gone'}
```
