### ISSUE TITLE
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 216.58.220.4:443

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/google-gdata#722]
```
   I am using Google Analytics task in SSIS.

Is there any problem with API. When there was a problem from 26th-May-2015 ,the 
data was not extracting from from 26th-May-2015 to 31st-may-2015 . After that 
it started extracting properly. Now again from 22nd-jun-2015 . Its not able to 
extract data. Its giving below error.

[SSIS GoogleAnalyticsSource] Error: Google.GData.Client.GDataRequestException: 
Execution of request failed: 
https://www.googleapis.com/analytics/v2.4/data?key=AIzaSyAfXg1iyNoEgJ-kMBaGbhN23
nNEXR2GVCA&dimensions=ga:country,ga:date&end-date=2015-05-26&filters=ga:country=
=United 
States&ids=ga:62691202&metrics=ga:bounces,ga:entrances,ga:newVisits,ga:pageviews
,ga:timeOnSite,ga:visitors,ga:visits&start-date=2015-05-26&segment=gaid::-1 
---> System.Net.WebException: Unable to connect to the remote server ---> 
System.Net.Sockets.SocketException: A connection attempt failed because the 
connected party did not properly respond after a period of time, or established 
connection failed because connected host has failed to respond 216.58.220.4:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at Google.GData.Client.Utilities.QueryClientLoginToken(GDataCredentials gc, String serviceName, String applicationName, Boolean fUseKeepAlive, IWebProxy proxyServer, Uri clientLoginHandler)
   at Google.GData.Client.GDataGAuthRequest.QueryAuthToken(GDataCredentials gc)
   at Google.GData.Client.GDataGAuthRequest.EnsureCredentials()
   at Google.GData.Client.GDataRequest.EnsureWebRequest()
   at Google.GData.Client.GDataGAuthRequest.EnsureWebRequest()
   at Google.GData.Client.GDataRequest.Execute()
   --- End of inner exception stack trace ---
   at Google.GData.Client.GDataRequest.Execute()
   at Google.GData.Client.GDataGAuthRequest.Execute(Int32 retryCounter)
   at Google.GData.Client.GDataGAuthRequest.Execute(Int32 retryCounter)
   at Google.GData.Client.GDataGAuthRequest.Execute(Int32 retryCounter)
   at Google.GData.Client.GDataGAuthRequest.Execute(Int32 retryCounter)
   at Google.GData.Client.GDataGAuthRequest.Execute()
   at Google.GData.Client.Service.Query(Uri queryUri, DateTime ifModifiedSince, String etag, Int64& contentLength)
   at Google.GData.Client.Service.Query(Uri queryUri, DateTime ifModifiedSince)
   at Google.GData.Client.Service.Query(FeedQuery feedQuery)
   at Google.GData.Analytics.AnalyticsService.Query(DataQuery feedQuery)
   at SSISComponents.GoogleAnalyticsSource.PrimeOutput(Int32 outputs, Int32[] outputIDs, PipelineB


Regards,
Megha Vaidya
```

Original issue reported on code.google.com by `webmas...@adcouncil.org` on 30 Jun 2015 at 10:53

**Comment by amritdorka** [comment]
facing the same issue.. did you find a solution for this..?

**Comment by sumeetmgit** [comment]
Facing same issue
